### ISSUE TITLE
Op checklist for developers

### ISSUE THREAD

**Issue by tibuch** [imagej/imagej-ops#207]
A checklist for op developers to verify an op implementation.

Op Checklist:
* [ ] ```@Plugin(type = ..., name = "...")```
* [ ] ```@Parameter(type = INPUT/OUTPUT)```
* [ ] Op description
* [ ] Parameter description 
* [ ] Op test
* [ ] Op namespace
* [ ] Op namespace test

This checklist should be part of #25.

**Comment by gab1one** [comment]
Also:
- [ ] Codestyle
- [ ] Best practices for performance
    - [ ]  Caching of OpService.
    - [ ] ...
- [ ] Checklist for good tests
    - [ ] Inherit AbstractOpTest 
    - [ ] ...

**Comment by ctrueden** [comment]
Would you care to make a wiki page?
https://github.com/imagej/imagej-ops/wiki

**Comment by imagejan** [comment]
I created a stub: https://github.com/imagej/imagej-ops/wiki/Op-checklist
Please enhance! ;-)

**Comment by ctrueden** [comment]
Thanks.
