### ISSUE TITLE
Add convolution/deconvolution ops

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-ops#70]
It would be awesome to provide a permissively licensed, high performance, general purpose deconvolution implementation in OPS. This entails work on several different constituent ops:

Milestones:
- [x] FFT, FHT, etc. – We can leverage ImgLib2's `FFTMethods` code (see also #12).
- [x] base classes for linear and iterative FFT filters.
- [x] FFT Version of Convolve
- [x] Richardson Lucy Deconvolution algorithm
- [x] Kernels – see also #48
- [x] Laplacian of Gaussian – in order to implement a complete segmentation pipeline.
- [ ] Separable-ND, Non-Separable-ND, NaiveConvolve – can leverage ImgLib2's `SeparableSymmetricConvolution`
- [ ] Fast, regularized version of Richardson Lucy with boundary conditions.  See [1] for possible approach (also @StephanPreibisch SPIM paper goes over some approaches [2])
- [ ] Diffraction based Point Spread Function Kernel (possibly wrap Icy plugin [3] or COSMOS, this would have to be licensed as gpl)
- [ ] Measured Point Spread Function Kernel (extract kernel from bead image)
- [ ] Common GPU infrastructure for above ops (covered separately by #60)

Considerations:
- [ ] Ops need to be "set" aware.  For example x-y-channels would be handled differently then x-y-z.   Need to read meta data (from ImgPlus?) 
- [ ] Usability.  Go over previous FFT and deconvolution questions on the listserv(s) and ensure above ops address community needs. 

See also:
- [This post on imagej-devel](http://imagej.net/pipermail/imagej-devel/2014-May/002091.html).
- #60 for related work—deconvolution on the GPU is an eventual goal.

[1] http://link.springer.com/chapter/10.1007%2F978-3-540-93860-6_81
[2] http://www.nature.com/nmeth/journal/v11/n6/full/nmeth.2929.html
[3] http://icy.bioimageanalysis.org/plugin/PSF_Generator

**Comment by bnorthan** [comment]
@ctrueden, @dscho, @dietzc, @StephanPreibisch 

I updated the "milestones" above to reflect recent work and what needs to be done next.   I can take a look at SymmetricSeparableConvolvolution next.  I also want to update all these ops for ImgPlus as ImgPlus enhancements are done.

**Comment by ctrueden** [comment]
Thanks @bnorthan for all your work on this!

On a general note: I want to keep these milestones achievable and granular. So e.g. for the GPU goals, those should be articulated separately in #60 and possibly other issues as appropriate, rather than blocking this issue from closing out once the initial work is complete.

Working on the SymmetricSeparableConvolution next makes sense. Hopefully it is a simple matter of wrapping the lower-level implementation. As always, speak up if any roadblocks.

**Comment by dietzc** [comment]
Some questions about the Convolver ops: Some implementations are using `Img` as input, rather than `RandomAccessibleInterval` or `RandomAccessible`. I think it would be a good idea to avoid  `Img` whenever possible. We should rather use the Ops-Conversion from `RandomAccessibleInterval` based ops to `Img` ops. 

What do you think @bnorthan @ctrueden?

**Comment by bnorthan** [comment]
Hi Christian

The convolver ops generally have two implementations, a higher level one using `Img` and a lower level one that uses `RandomAccessibleInterval`.  

The high level op uses the `ImgFactory` of the input to create the output, and to create memory for the FFT (if it is an FFT based convolver).   The high level op(s) also extend the input and kernel (if required).    In the future the high level op will look at the meta data to determine the type of the axis (this is needed so that XYZ (3D convolution) can be handled differently than XYT (a series of 2D convolutions)).  

The low level ones, that use `RandomAccessibleInterval` do the actual work and can be called directly if everything is already set up. 

Do you think it is possible to to totally bypass `Img`??  I'm not sure I understand how to get the `ImgFactory` in that case.   

I know we could pass in the `ImgFactory` but that makes the signature more complicated.  If you have thoughts regarding a more elegant design, let me know.  I am happy to make changes.

**Comment by dietzc** [comment]
Hi Brian,

I think this is going to be a very fundamental discussion now, maybe @ctrueden @hinerm can also comment on this. My opinion regarding `Img` is as follows:

We should always void using `Img`, as it basically acts like an  `RandomAccessibleInterval` (you can get the `IterableInterval` via `Views`). The only problem, as you already mentioned, is the `ImgFactory`. An user can always set the output `RandomAccessibleInterval`, `IterableInterval`, etc from outside and therefore control the underlying factory type of the output. If the user doesn't provide an output, we have to have a smart, but very general mechanism, which knows how to create appropriate outputs. For me this mechanism is implemented using the `CreateImg` interface. We have several input options here: If the incoming `RandomAccessibleInterval` actually is an `Img` (`instanceof` test ... even extendible for other types?!) we can use the same `ImgFactory`, if not, we have to use a smart heuristic which checks if we can use an `ArrayImgFactory` or a CellImgFactory`. But this should be encapsulated in the `CreateImg`. 

In an `Op` which can create an output given some `RandomAccessibleInterval` and maybe an `Type` we would always just call `CreateImg` given some parameters. Of course we have to implement many `Op`s using `CreateImg` for all the permutations of `Interval`, `Type`, `ImgFactory` etc.. @danielseebacher and @tibuch will take care about this in the next couple of weeks (see https://github.com/imagej/imagej-ops/issues/96). CreateLabeling btw. will act the same.

Does this make sense? Comments?

**Comment by bnorthan** [comment]
Hi Christian

>We have several input options here: If the incoming RandomAccessibleInterval actually is an Img >(instanceof test ... even extendible for other types?!) we can use the same ImgFactory 

'Ideally' the ops I've written that use `Img` will be minimal (I still need to clean them up a bit to make sure they are as minimal as possible).  Essentially they are using the ops framework to determine what type we have.  If it's `Img` then the ops framework calls the `Img` version, which gets the `ImgFactory` from the `Img`,  then the `RandomAccessibleInterval` version is called.

Is this OK??  Or do you think it would be better to just have one Op and do the `instanceof` test??  Either way is fine with me as long as we can handle all scenarios smoothly.  For example what if we need meta-data??  Like axis type or calibrations?  Long term are we looking at using ImgPlus for that anyway??  

Please feel free to review the convolution ops with a critical eye. Even though the pull request was merged more review wouldn't be a bad thing.

**Comment by dietzc** [comment]
Hi Brian,

you are absolutely right, `ImgPlus` must also be considered. I think this discussion is similar to a discussion @ctrueden and I had a while ago: If we determine a pattern, for instance, for every Op which bases on a `RandomAccessibleInterval` input we have another Op with `Img` or `ImgPlus`, can we implicitly convert the `RandomAccessibleInterval` based operation?  

The advantage having all "heuristics" in a central `CreateImg` or `CreateLabeling` or ... is, that the behaviour is certainly the same for all `Op`s, which are using the above mentoined ones.

I don't want to be too anal, but I'm running into similar problems with other `Op`s at the moment and I hope we can find a unified solution.

**Comment by ctrueden** [comment]
It's hard for me to find time to think about the "high-level" vs. "low-level" issue, but I'll try to do a quick brain dump here, since it's a hot topic.

* The `Img` vs. `RandomAccessibleInterval` case isn't the only one. We also have `ImgPlus` vs. `Img` and similar.
* The issue comes down to whether the richer data object has any additional information that is useful to the op in question. The common pattern seems to be that there is extra useful-but-not-strictly-necessary information. E.g., an `ImgPlus` gives an `Axis` list that is handy, but default assumptions can be made in the case of `Img` or other `EuclideanSpace`.
* Or in some cases, the extra info is necessary, but can be provided separately. E.g., an `ImgFactory` in the case of a lower level data object than `Img`.
* So, it seems we could simply write the op to the lower level spec (e.g., with `RandomAccessibleInterval` and `ImgFactory` args) then have an op reducer (see #39) that converts calls with an `Img` to the other signature by grabbing the factory from the `Img`.
* The trouble with op reducers will be type-safe method signatures. So another approach is to follow a type-safe pattern where we do in fact have two ops that extend a common abstract type that keeps things DRY—i.e., takes care of the repeated work of extracting `ImgFactory` from `Img`, and similar code for other common cases.

I guess I don't feel too strongly about exactly how it is done, but do want to see the code avoid repetition whenever possible. DRY, DRY, DRY...

**Comment by bnorthan** [comment]
@kbellve has a huge amount of decon related code that would be very useful to ops.  State of the art stuff including GPU.  Karl this issue is where we are keeping track of the progress of ops deconvolution.  Please feel free to chime in.

**Comment by bnorthan** [comment]
@chalkie666 has written a script 

"Showing a simulation of the systematic error effect of the objecive lens OTF (similar to a Gaussian blur) on the contrast of different spatial frequencies in a light microscopy image.  Showing why optical microscope images should be deconvolved,to correct the systematic error of contrast vs. feature size: Contrast of smaller and smaller features is attenuatted more and more, up to the bad limit or noise floor, where deconvolution can no longer recover info."

https://github.com/chalkie666/imagejMacros/blob/master/exponentialChirpImag.ijm

Much of this code could be converted to ops tests and script examples.
